### ISSUE TITLE
biosecurity query fails ? :   SDF.parse is to parse date string to Date

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/alerts#201]
https://github.com/AtlasOfLivingAustralia/alerts/blame/917424fff3f2b75e169ca048db8ac4dabcd259c8/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L699

@adam-collins  I don't think this line works.  sdf.parse only  accepts date string

Another question is:  Shall we use our Local Date or UTC date to search on Biocache?

**Comment by adam-collins** [comment]
You will need to use the functional requirements that I hope are now available; when it is run (weekday/time), how it is run (a button click or schedule), any staging/manual review steps in place before emails are sent.

As for your second question, the SOLR date format `yyyy-MM-ddThh:mm:ssZ`'s Z denotes UTC.

There were no resources available to provide the missing requirements 5 months ago therefore it is not finished and not expected to work as-is. The expectation was that the requirements would be provided at the time and the code finished. Since this was unmet, and much time passed, it was forgotten. 

It looks like a modified copy and paste of the test function used by the UI.

**Comment by qifeng-bai** [comment]
Thanks for your confirmation.  I will fix it
