### ISSUE TITLE
User cannot see their own custom alerts (biosecurity alerts)

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#213]
After a user is signed up to a biosecurity alert:

1. When logged in as an ALA Admin, on alerts-test (https://alerts-test.ala.org.au/admin/user), I can see their regular subscriptions, as well as any biosecurity alerts listed under  "My custom alerts"
<img width="638" alt="Screenshot 2024-05-08 at 3 34 24 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/763c0995-bd0e-4ed4-948d-642b8326abb0">

2. But when I log in as that user, and view "My alerts" from my profile (https://alerts-test.ala.org.au/notification/myAlerts), I can only see the regular alerts and other custom alerts, if applicable, not the biosecurity alerts (other custom alerts can be added ok):
<img width="738" alt="Screenshot 2024-05-08 at 4 03 50 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/a6fcf127-b07f-4ddc-adb3-828ea7908bd5">

**Comment by kylie-m** [comment]
Follow up: I'm quite convinced this is due to duplicate accounts sitting in alerts-test -  doing further testing

**Comment by kylie-m** [comment]
This does seem to be fine for a completely new user account, email address never used before. 

user view and Admin view match:
<img width="2087" alt="Screenshot 2024-05-08 at 5 30 12 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/60d3e94a-17aa-40ef-bd1f-5f61940fe9ce">

**Comment by qifeng-bai** [comment]
Also refer the answer in #214 

There are two Primary key: **user ID and user Email**  used in Alerts.

the "user ID" is used to find the alerts/queries linked to this user account. 
the "user Email" is used when we subscribe /unsubscribe a query

When we delete a user and created again with the same email address, what happens in Alerts:
The "new user" cannot see the "previous" subscriptions in myAlerts page, although the user has the same email before, because it is a **new** user to the Alerts system 

However, when the admin subscribe this user to a query,  the Alerts only cares about the 'Email' address. What happened in DB, the Alerts will search the user table with the email address, and link **the first matched user** into the subscription
