### ISSUE TITLE
-taxon_name: function not excluding taxa in alerts

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#249]
[BioSecurity alert for QLD_DAF_InvasivePestsAnimals_list](https://lists.ala.org.au/speciesListItem/list/dr27365) contains a number of taxon names that should be excluded, including Vachellia farnesiana. 

The relevant query is in the FQ column, but occurrences of this excluded species are showing in alerts: 
![image](https://github.com/user-attachments/assets/f74495ca-9b67-4674-82e5-1928a34534e8)

**Comment by turley85** [comment]
Note: This list is an example where alerts are setup for "Vachellia", but specific species (e.g. Vachellia farnesiana) have been specifically excluded.

**Comment by kylie-m** [comment]
Hi @turley85, looking at your list, I noticed there was one row with Vachellia (genus), with fq column constraining to an area but without any taxon exclusions. I've tested a shorter version of your list (see https://lists.ala.org.au/speciesListItem/list/dr27372), adding the taxon exclusion to the Vachellia genus, and it seems to be working now in alerts. 

On a side note, I also noticed you have Vachellia nilotica added to the list but then have excluded the species in the fq, and same for Vachellia farnesiana - I wanted to check if that's intentional, such as to pick up subspecies/varieties/etc?

**Comment by turley85** [comment]
Thanks @kylie-m, 

Adding the excluded taxon in the list is the standard way it was working in R, hence the current format of the lists. 

Good to know it works if the -taxon query is included in the fq field the genus itself. I'll need to check if there's any scenarios where a taxon needs to be excluded but not associated with a genus. (I can't think of one right now, but will check).

**Comment by kylie-m** [comment]
Thanks Andrew, I'll mark this one as closed now :)
